- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Download code
  ansible.builtin.include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: /usr/share/nginx/html

- name: Copy HTTP docs file
  ansible.builtin.template:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: start the nginx services
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes


